import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Footer ,Navbar} from "@/components";
import ClientProvider from '@/components/ClientProvider'; 




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientProvider>
     
          <Navbar />
          <main className="main-container">
            {children}
          </main>
          <Footer />
          </ClientProvider>
         
       
      </body>
    </html>
  );
}
